version: "3.3"
services:

  googledrive:
    volumes:
      - .:/app
    environment:
      - SERVER_HOST=http://${DOMAIN?Variable not set}
      - PORT=${GOOGLEDRIVE_PORT}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    labels:
      - traefik.enable=true
      - traefik.constraint-label-stack=${TRAEFIK_TAG?Variable not set}
      - traefik.http.routers.${STACK_NAME?Variable not
        set}-googledrive-http.rule=PathPrefix(`/googledrive`)
      - traefik.http.services.${STACK_NAME?Variable not
        set}-googledrive.loadbalancer.server.port=${GOOGLEDRIVE_PORT}
      - traefik.http.routers.${STACK_NAME?Variable not set}-googledrive-http.middlewares=googledrive-stripprefix
      - traefik.http.middlewares.googledrive-stripprefix.stripprefix.prefixes=/googledrive
