version: "3.7"
services:

  googledrive:
    image: 'googledrivedev'
    container_name: googledrive-integrated
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - PORT
      - BASE_PATH=/googledrive
      - MONGODB_URL=mongodb://user:userpass@mongodb:27017/data?retryWrites=true&w=majority
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.${STACK_NAME?Variable not set}-googledrive-http.rule=PathPrefix(`/googledrive`)
      - traefik.http.services.${STACK_NAME?Variable not set}-googledrive.loadbalancer.server.port=${PORT}
      - traefik.http.routers.${STACK_NAME?Variable not set}-googledrive-http.middlewares=googledrive-stripprefix
      - traefik.http.middlewares.googledrive-stripprefix.stripprefix.prefixes=/googledrive
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
