version: "3.3"
services:

  googledrive:
    container_name: googledrive-solo
    volumes:
      - .:/app
    environment:
      - SERVER_HOST=http://${DOMAIN?Variable not set}
      - BASE_PATH=
      - PORT
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    ports:
      - "${SOLODEVPORT}:${PORT}"
    networks:
      - default